# Generated by Django 4.0.1 on 2022-02-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=25)),
                ('age', models.CharField(max_length=25)),
                ('event', models.CharField(max_length=25)),
                ('venues', models.CharField(max_length=25)),
                ('area', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('pincode', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=25)),
            ],
        ),
    ]
