# Generated by Django 4.0.1 on 2022-02-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(),
        ),
    ]
