# Generated by Django 4.0.1 on 2022-02-26 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atapp', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
