# Generated by Django 3.2.10 on 2022-03-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atapp', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
