# Generated by Django 3.2.10 on 2022-03-31 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atapp', '0010_auto_20220331_0113'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
