# Generated by Django 3.2.10 on 2022-04-03 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atapp', '0012_uploadimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadImage',
        ),
    ]
