# Generated by Django 3.2.10 on 2022-04-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atapp', '0015_auto_20220403_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='static/assets/profile/')),
            ],
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
