# Generated by Django 3.2.10 on 2022-04-21 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atapp', '0020_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='profileuser',
        ),
    ]
