# Generated by Django 3.2.10 on 2022-04-22 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Atapp', '0021_rename_user_profile_profileuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='dashuser',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Book', to='auth.user'),
            preserve_default=False,
        ),
    ]
