# Generated by Django 3.2.10 on 2022-04-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atapp', '0022_book_dashuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
