# Generated by Django 3.2.10 on 2022-04-23 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Atapp', '0027_alter_book_dashuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='dashuser',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Dashuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
