# Generated by Django 3.2.10 on 2022-04-26 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atapp', '0029_alter_book_dashuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='area',
        ),
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
        migrations.RemoveField(
            model_name='book',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='book',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pincode',
        ),
        migrations.AddField(
            model_name='book',
            name='acnonac',
            field=models.CharField(choices=[('Ac', 'Ac'), ('Non-Ac', 'Non-Ac')], default='AC', max_length=10),
        ),
        migrations.AddField(
            model_name='book',
            name='decorations',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AddField(
            model_name='book',
            name='doe',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='book',
            name='estimation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='food',
            field=models.CharField(default='null', max_length=12),
        ),
        migrations.AddField(
            model_name='book',
            name='music',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='YES', max_length=5),
        ),
        migrations.AddField(
            model_name='book',
            name='name',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='plate',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='others', max_length=7),
        ),
        migrations.AlterField(
            model_name='book',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
