# Generated by Django 3.2.10 on 2022-04-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atapp', '0030_auto_20220426_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
