# Generated by Django 3.2.10 on 2022-04-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atapp', '0031_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='phone',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
