# Generated by Django 3.2.10 on 2022-04-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atapp', '0033_alter_book_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='decorations',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Paid', 'Paid')], default='Pending', max_length=20),
        ),
    ]
